name = "Pset1"
uuid = "eb8caa2f-a84c-4d26-8523-499f1e7561f2"
authors = ["Kavi Gupta"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
